name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  flutter_hooks: ^0.18.5+1
  badges: ^2.0.3
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/earphone/
    - assets/icons/